### ISSUE TITLE
Deprecated Repository 2.1

### ISSUE THREAD

**Issue by catbus00** [Code-the-Dream-School/react#7]
The guessing game is running on a old npm version that does not work with the latest npm and should be updated accordingly. It currently only runs on legacy code: npm install react-scripts@latest --legacy-peer-deps

**Comment by JamieBort** [comment]
Hi, @royemosby . Does this still need to be addressed?
I am looking for Issues to work on.
If this does not need to be addressed, I'd like to find a TypeScript Issue to work on; if those exist in this CtD account.
Otherwise I try to contribute wherever I'm needed.

Please let me know if you're aware of a more pressing Issue.

FWIW, I just posted this comment: https://github.com/Code-the-Dream-School/school-pages/issues/4#issuecomment-2035351700

Thanks, Roy!

**Comment by royemosby** [comment]
@JamieBort thanks for offering! As of right now, it's up in the air what sort of curriculum updates need to happen. I'm expecting to hear more about CTD's curriculum update strategy from @mamooredesigns when CTD leadership has made some admin decisions.

**Comment by JamieBort** [comment]
Hi, @royemosby. Thank you for letting me know. 

My motivation is I'd like to continue to give back to CtD. Whereas before I was doing more mentorship, I would like to start writing code more.

I do not mind looking in https://github.com/Code-the-Dream-School/ on my own. But as I was looking around I realized that there are many repos. And I wasn't sure where to start or focus my search.

If when, Issues come up that could use some love, I'd like to contribute. Particularly if they're Typescript, Node, or JavaScript. (I'd say Java too but we don't do that here.)

And if you think other CtD members might be aware of any Issues to work on, please feel free to let them know too. If you think it is pertinent. Thanks again, Roy!

**Comment by royemosby** [comment]
@JamieBort I'll keep you in the know for sure! More hands make for less work.

**Comment by JamieBort** [comment]
Thank you! Agreed.

**Comment by mamooredesigns** [comment]
Fixed in Feb 2024
